// Code generated by mockery v2.53.3. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSubPub is an autogenerated mock type for the SubPub type
type MockSubPub struct {
	mock.Mock
}

type MockSubPub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubPub) EXPECT() *MockSubPub_Expecter {
	return &MockSubPub_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *MockSubPub) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubPub_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSubPub_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSubPub_Expecter) Close(ctx interface{}) *MockSubPub_Close_Call {
	return &MockSubPub_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockSubPub_Close_Call) Run(run func(ctx context.Context)) *MockSubPub_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSubPub_Close_Call) Return(_a0 error) *MockSubPub_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubPub_Close_Call) RunAndReturn(run func(context.Context) error) *MockSubPub_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: subject, msg
func (_m *MockSubPub) Publish(subject string, msg interface{}) error {
	ret := _m.Called(subject, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(subject, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubPub_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockSubPub_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - subject string
//   - msg interface{}
func (_e *MockSubPub_Expecter) Publish(subject interface{}, msg interface{}) *MockSubPub_Publish_Call {
	return &MockSubPub_Publish_Call{Call: _e.mock.On("Publish", subject, msg)}
}

func (_c *MockSubPub_Publish_Call) Run(run func(subject string, msg interface{})) *MockSubPub_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockSubPub_Publish_Call) Return(_a0 error) *MockSubPub_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubPub_Publish_Call) RunAndReturn(run func(string, interface{}) error) *MockSubPub_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: subject, cb
func (_m *MockSubPub) Subscribe(subject string, cb MessageHandler) (Subscription, error) {
	ret := _m.Called(subject, cb)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, MessageHandler) (Subscription, error)); ok {
		return rf(subject, cb)
	}
	if rf, ok := ret.Get(0).(func(string, MessageHandler) Subscription); ok {
		r0 = rf(subject, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, MessageHandler) error); ok {
		r1 = rf(subject, cb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubPub_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockSubPub_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - subject string
//   - cb MessageHandler
func (_e *MockSubPub_Expecter) Subscribe(subject interface{}, cb interface{}) *MockSubPub_Subscribe_Call {
	return &MockSubPub_Subscribe_Call{Call: _e.mock.On("Subscribe", subject, cb)}
}

func (_c *MockSubPub_Subscribe_Call) Run(run func(subject string, cb MessageHandler)) *MockSubPub_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(MessageHandler))
	})
	return _c
}

func (_c *MockSubPub_Subscribe_Call) Return(_a0 Subscription, _a1 error) *MockSubPub_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubPub_Subscribe_Call) RunAndReturn(run func(string, MessageHandler) (Subscription, error)) *MockSubPub_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubPub creates a new instance of MockSubPub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubPub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubPub {
	mock := &MockSubPub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
